/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import { core } from '@nexus/schema'
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<'inputTypes', TypeName, FieldName>
      >,
    ): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void // "Date";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenRootTypes {
  Mutation: {}
  Post: {
    // root type
    content?: string | null // String
    id: number // Int!
    published: boolean // Boolean!
    title: string // String!
  }
  Query: {}
  User: {
    // root type
    email: string // String!
    id: number // Int!
    name: string // String!
  }
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  String: NexusGenScalars['String']
  Int: NexusGenScalars['Int']
  Float: NexusGenScalars['Float']
  Boolean: NexusGenScalars['Boolean']
  ID: NexusGenScalars['ID']
  Date: NexusGenScalars['Date']
}

export interface NexusGenFieldTypes {
  Mutation: {
    // field return type
    createDraft: NexusGenRootTypes['Post'] // Post!
    deletePost: NexusGenRootTypes['Post'] | null // Post
    publish: NexusGenRootTypes['Post'] | null // Post
    signupUser: NexusGenRootTypes['User'] // User!
  }
  Post: {
    // field return type
    author: NexusGenRootTypes['User'] | null // User
    content: string | null // String
    id: number // Int!
    published: boolean // Boolean!
    title: string // String!
  }
  Query: {
    // field return type
    drafts: NexusGenRootTypes['Post'][] // [Post!]!
    feed: NexusGenRootTypes['Post'][] // [Post!]!
    filterPosts: NexusGenRootTypes['Post'][] // [Post!]!
    post: NexusGenRootTypes['Post'] // Post!
  }
  User: {
    // field return type
    email: string // String!
    id: number // Int!
    name: string // String!
    posts: NexusGenRootTypes['Post'][] // [Post!]!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDraft: {
      // args
      authorEmail?: string | null // String
      content?: string | null // String
      title: string // String!
    }
    deletePost: {
      // args
      postId?: string | null // String
    }
    publish: {
      // args
      postId?: string | null // String
    }
    signupUser: {
      // args
      email: string // String!
      name?: string | null // String
    }
  }
  Query: {
    filterPosts: {
      // args
      searchString?: string | null // String
    }
    post: {
      // args
      postId: string // String!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = 'Mutation' | 'Post' | 'Query' | 'User'

export type NexusGenInputNames = never

export type NexusGenEnumNames = never

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames =
  | 'Boolean'
  | 'Date'
  | 'Float'
  | 'ID'
  | 'Int'
  | 'String'

export type NexusGenUnionNames = never

export interface NexusGenTypes {
  context: any
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  allTypes: NexusGenAllTypes
  inheritedFields: NexusGenInheritedFields
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
}
