// flow-typed signature: 8ec4cddf0d6eabd3cda1fec4028e9712
// flow-typed version: <<STUB>>/graphql-resolver-codegen_v0.2.7/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-resolver-codegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-resolver-codegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-resolver-codegen/dist/generators/flow-generator' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/flow-scaffolder' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/generator-interface' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/reason-generator' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/reason-scaffolder' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/ts-generator' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/generators/ts-scaffolder' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-resolver-codegen/dist/source-helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-resolver-codegen/dist/generators/flow-generator.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/flow-generator'>;
}
declare module 'graphql-resolver-codegen/dist/generators/flow-scaffolder.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/flow-scaffolder'>;
}
declare module 'graphql-resolver-codegen/dist/generators/generator-interface.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/generator-interface'>;
}
declare module 'graphql-resolver-codegen/dist/generators/reason-generator.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/reason-generator'>;
}
declare module 'graphql-resolver-codegen/dist/generators/reason-scaffolder.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/reason-scaffolder'>;
}
declare module 'graphql-resolver-codegen/dist/generators/ts-generator.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/ts-generator'>;
}
declare module 'graphql-resolver-codegen/dist/generators/ts-scaffolder.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/generators/ts-scaffolder'>;
}
declare module 'graphql-resolver-codegen/dist/index.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/index'>;
}
declare module 'graphql-resolver-codegen/dist/source-helper.js' {
  declare module.exports: $Exports<'graphql-resolver-codegen/dist/source-helper'>;
}
