// flow-typed signature: 1ad19635e1020c03f3e370f5f0d6e371
// flow-typed version: <<STUB>>/prisma_v1.17.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prisma/dist/index.js' {
  declare module.exports: $Exports<'prisma/dist/index'>;
}
