// flow-typed signature: 3aa542cf70bc73cf6bacc34ef1f7ac47
// flow-typed version: <<STUB>>/prisma-client-lib_v1.17.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma-client-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma-client-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma-client-lib/dist/Client' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/flow-client' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/flow-client.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/Generator' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/go-client' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/go-client.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/javascript-client' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/javascript-client.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/types' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/typescript-client.airbnb.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/typescript-client' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/typescript-client.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/typescript-definitions' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/typescript-definitions.test' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/utils/flatten' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/codegen/utils/interleave' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/index' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/makePrismaClientClass' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/types' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/codeComment' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/getTypeNames' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/index' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/mapAsyncIterator' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/mapValues' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/observableToAsyncIterable' {
  declare module.exports: any;
}

declare module 'prisma-client-lib/dist/utils/removeKey' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prisma-client-lib/dist/Client.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/Client'>;
}
declare module 'prisma-client-lib/dist/codegen/flow-client.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/flow-client'>;
}
declare module 'prisma-client-lib/dist/codegen/flow-client.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/flow-client.test'>;
}
declare module 'prisma-client-lib/dist/codegen/Generator.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/Generator'>;
}
declare module 'prisma-client-lib/dist/codegen/go-client.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/go-client'>;
}
declare module 'prisma-client-lib/dist/codegen/go-client.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/go-client.test'>;
}
declare module 'prisma-client-lib/dist/codegen/javascript-client.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/javascript-client'>;
}
declare module 'prisma-client-lib/dist/codegen/javascript-client.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/javascript-client.test'>;
}
declare module 'prisma-client-lib/dist/codegen/types.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/types'>;
}
declare module 'prisma-client-lib/dist/codegen/typescript-client.airbnb.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/typescript-client.airbnb.test'>;
}
declare module 'prisma-client-lib/dist/codegen/typescript-client.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/typescript-client'>;
}
declare module 'prisma-client-lib/dist/codegen/typescript-client.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/typescript-client.test'>;
}
declare module 'prisma-client-lib/dist/codegen/typescript-definitions.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/typescript-definitions'>;
}
declare module 'prisma-client-lib/dist/codegen/typescript-definitions.test.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/typescript-definitions.test'>;
}
declare module 'prisma-client-lib/dist/codegen/utils/flatten.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/utils/flatten'>;
}
declare module 'prisma-client-lib/dist/codegen/utils/interleave.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/codegen/utils/interleave'>;
}
declare module 'prisma-client-lib/dist/index.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/index'>;
}
declare module 'prisma-client-lib/dist/makePrismaClientClass.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/makePrismaClientClass'>;
}
declare module 'prisma-client-lib/dist/types.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/types'>;
}
declare module 'prisma-client-lib/dist/utils/codeComment.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/codeComment'>;
}
declare module 'prisma-client-lib/dist/utils/getTypeNames.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/getTypeNames'>;
}
declare module 'prisma-client-lib/dist/utils/index.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/index'>;
}
declare module 'prisma-client-lib/dist/utils/mapAsyncIterator.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/mapAsyncIterator'>;
}
declare module 'prisma-client-lib/dist/utils/mapValues.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/mapValues'>;
}
declare module 'prisma-client-lib/dist/utils/observableToAsyncIterable.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/observableToAsyncIterable'>;
}
declare module 'prisma-client-lib/dist/utils/removeKey.js' {
  declare module.exports: $Exports<'prisma-client-lib/dist/utils/removeKey'>;
}
