// flow-typed signature: e316a84af6ef2a92def0dbe41f30a8f8
// flow-typed version: <<STUB>>/graphql-yoga_v^1.16.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-yoga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-yoga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-yoga/dist/defaultErrorFormatter' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/index.test' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/lambda' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-yoga/dist/defaultErrorFormatter.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/defaultErrorFormatter'>;
}
declare module 'graphql-yoga/dist/index.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/index'>;
}
declare module 'graphql-yoga/dist/index.test.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/index.test'>;
}
declare module 'graphql-yoga/dist/lambda.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/lambda'>;
}
declare module 'graphql-yoga/dist/types.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/types'>;
}
