name: test
on:
  push:
    paths:
      - orm/**
      - databases/**
      - tests/**
      - package.json
      - vitest.config.ts
    branches:
      - latest
  pull_request:

env:
  CI: 1
  PRISMA_TELEMETRY_INFORMATION: 'prisma-examples test.yaml'
  SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
  SKIP_PRISMA_VERSION_CHECK: true

jobs:
  test:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
