name: test-sql-server
on:
  push:
    paths:
      - databases/sql-server/**
    branches:
      - latest
      - dev
      - patch-dev
  pull_request:
    paths:
      - databases/sql-server/**

env:
  CI: 1
  PRISMA_TELEMETRY_INFORMATION: 'prisma-examples test-sql-server.yaml'

jobs:
  test:
    defaults:
      run:
        working-directory: databases/sql-server
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      sql-server:
        # Docker Hub image
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 'Pr1sm4_Pr1sm4'
        # Maps tcp port 1433 on service container to the host
        ports:
          - '1433:1433'
        options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: sqlserver://localhost:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npx prisma migrate dev --name "init"
      - run: npm run test
